name: PR title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read
  pull-requests: read

jobs:
  commitizen:
    name: Commitizen
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: uvx --from commitizen cz check --message "$PR_TITLE"
